const express = require('express')
const app = express()
app.set('views', "Pages")
app.set('view engine', 'ejs')
app.use(express.json())
app.use(express.urlencoded({extended: true}))
app.use(require('cookie-parser')())
app.use("/",require('./routes/custompages'))
app.use("/",require('./routes/api'))
app.use("/cdn/css",require('./routes/css'))
app.use("/cdn/js",require('./routes/js'))
app.disable('x-powered-by')
//catch all route
app.all("*",(req,res)=>{
    console.log(req.url)
    console.log(req.hostname)
    console.log(req.method)
    console.log(req.body)
    res.status(404).send()
})
process.on('uncaughtException',(e)=>{
    console.log(e)
})
app.listen(42069, () => {
    console.log(`listenin on port 42069`)
})